language:
  - swift

os:
  - osx

osx_image:
  - xcode10.2

script:
  - xcodebuild test -project RandomUserSwiftyiOSExample.xcodeproj -scheme RandomUserSwiftyiOSExample -destination "platform=iOS Simulator,name=iPhone XS"
