os:
  - osx

osx_image:
  - xcode10.1

script:
  - xcodebuild test -project RandomUserSwiftyiOSExample.xcodeproj -scheme RandomUserSwiftyiOSExample -destination "platform=iOS Simulator,name=iPhone XS"
